const mongoose = require("mongoose");
const userSchema = new mongoose.Schema({
  visited: Date,
  available: mongoose.Schema.Types.Mixed,
  contact : String,
  rentOrSell: String,
  type: String,
  condition: String,
  city: String,
  neighborhood: String,
  street: String,
  streetNumber: String,
  squareMeter: Number,
  rooms: Number,
  floor: Number,
  maxFloor: Number,
  balcony: Number,
  serviceBalcony: Number,
  parking: Number,
  warehouse: Number,
  bathrooms: Number,
  bathtub: String,
  showerStall: String,
  elevator: Number,
  safeRoom : Number,
  airConditioner: Array,
  furniture:Array,
  airDirections: Array,
  extended: Array,
  propertyTax: Number,
  committee: Number,
  price: Number,
});
userSchema.pat
const UserModel = mongoose.model("properties", userSchema);
module.exports = UserModel;
